[package]
name = "necstar-py"
version = "0.1.0"
edition = "2021"

[lib]
name = "necstar"
crate-type = ["cdylib", "rlib"]

[dependencies]
pyo3 = { version = "0.21", features = ["extension-module", "num-complex"] }
num-complex = "*"
stab-decomp-simulator-rust = { path = "../core" }